CREATE TABLE `dev_cabinet` (
  `cabinet_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `cabinet_sn` varchar(64) NOT NULL COMMENT '电柜序列号',
  `cabinet_model` varchar(32) DEFAULT NULL COMMENT '电柜型号',
  `cabinet_name` varchar(100) DEFAULT NULL COMMENT '电柜名称',
  `cabinet_gate_count` int DEFAULT NULL COMMENT '仓门数量',
  `cabinet_status` tinyint NOT NULL DEFAULT '0' COMMENT '状态 0：未激活 1：已激活 2：维护中 3：已退库',
  `cabinet_protocol` tinyint NOT NULL DEFAULT '1' COMMENT '协议类型 1：铁塔协议',
  `first_report_time` datetime DEFAULT NULL COMMENT '首次上报时间',
  `last_report_time` datetime DEFAULT NULL COMMENT '最后上报时间',
  `manufacturer` varchar(100) DEFAULT NULL COMMENT '制造商',
  `firmware_version` varchar(32) DEFAULT NULL COMMENT '固件版本',
  `installed_date` datetime DEFAULT NULL COMMENT '安装时间',
  `coordinates` varchar(100) DEFAULT NULL COMMENT '安装位置经纬度',
  `province` varchar(32) DEFAULT NULL COMMENT '省',
  `city` varchar(32) DEFAULT NULL COMMENT '市',
  `district` varchar(32) DEFAULT NULL COMMENT '区',
  `address` varchar(255) DEFAULT NULL COMMENT '详细地址',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标记 0：未删除 1：已删除',
  PRIMARY KEY (`cabinet_id`),
  UNIQUE KEY `uk_cabinet_sn` (`cabinet_sn`),
  KEY `idx_cabinet_status` (`cabinet_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='电柜信息表';